name: CI/CD Build Pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: './car-rental/package-lock.json'

      - name: Install dependencies & Build frontend
        working-directory: ./car-rental
        run: |
          npm ci
          npm run build

      # Налаштовуємо інструмент для збірки Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Перевіряємо збірку фронтенду
      - name: Build Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./car-rental
          file: ./car-rental/Dockerfile
          push: false
          tags: luxedrive-frontend:latest

      # Перевіряємо збірку бекенду
      - name: Build Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./car-rental-api
          file: ./car-rental-api/Dockerfile
          push: false
          tags: luxedrive-backend:latest
